Resources:
  RDSProxyRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Sls_RDSProxyRole_${self:service}_${opt:stage}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 'sts:AssumeRole'
            Principal:
              Service: 'rds.amazonaws.com'
      Policies:
        - PolicyName: Sls_RDSProxyRole_${self:service}_${opt:stage}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: '*'
                Resource: '*'

  RDSSecurityGroup:
    DependsOn: RDSProxyRole
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Sls_RDSSecurityGroup_${self:service}_${opt:stage}
      GroupDescription: Serverless RDS Security Group
      VpcId: vpc-0b2fd3a9be1439609 # The main VPC ID
      SecurityGroupIngress:
        - Description: Allow
          IpProtocol: '-1'
          FromPort: '-1'
          ToPort: '-1'
          CidrIp: 0.0.0.0/0

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
      EngineVersion: '13.7'
      DBInstanceIdentifier: db-${self:service}-${opt:stage} # A name for the DB instance
      DBName: Upworddatabase
      MasterUsername: ${env:DB_USERNAME}
      MasterUserPassword: ${env:DB_PASSWORD}
      DBInstanceClass: ${env:DB_SIZE}
      AllocatedStorage: ${env:DB_STORAGE}
      MaxAllocatedStorage: ${env:DB_MAX_STORAGE}
      PubliclyAccessible: true
      EnablePerformanceInsights: ${env:PERFORMANCE_INSIGHTS} # Enable Performance Insights for the DB instance
      MultiAZ: ${env:MULTI_AZ} # Specifies whether the database instance is a Multi-AZ DB instance deploymen
      BackupRetentionPeriod: 7 # The number of days for which automated backups are retained
      PreferredMaintenanceWindow: 'Sun:02:00-Sun:03:00' # Format: ddd:hh24:mi-ddd:hh24:mi
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
