name: Workflow API
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Continuous Integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    environment: dev
    env:
      DB_USERNAME: ${{ vars.DB_USERNAME }}
      DB_NAME: ${{ vars.DB_NAME }}
      DB_HOST: ${{ vars.DB_HOST }}
      DB_PASSWORD: ${{ vars.DB_PASSWORD }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_SIZE: ${{ vars.DB_SIZE }}
      DB_STORAGE: ${{ vars.DB_STORAGE }}
      DB_MAX_STORAGE: ${{ vars.DB_MAX_STORAGE }}
      MULTI_AZ: ${{ vars.MULTI_AZ }}
      PERFORMANCE_INSIGHTS: ${{ vars.PERFORMANCE_INSIGHTS }}
      MONITORING_INTERVAL: ${{ vars.MONITORING_INTERVAL }}
      LOG_RETENTION_DAYS: ${{ vars.LOG_RETENTION_DAYS }}
      LAMBDA_MEMORY_SIZE: ${{ vars.LAMBDA_MEMORY_SIZE }}

    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci

      - name: Setting Aws keys
        run: |
          aws configure set aws_access_key_id ${{ secrets.ACCESS_KEY }} --profile default
          aws configure set aws_secret_access_key ${{ secrets.SECRET_ACCESS_KEY }} --profile default

      - name: Serverless Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          npx serverless deploy --stage dev
